### PR TITLE
Fixed typo 'requeriments' =>'requirements'

### PR DESCRIPTION
**Pull request by ArgonQQ**

### CODE REVIEW

**Comment by AlMaVizca** [comment]
Thank you :)

**Comment by ArgonQQ** [comment]
No problem! I could update some missing php extensions aswell or was a "minimal" setup your intention? 

Greetings! 
~ Marcel

**Comment by AlMaVizca** [comment]
Yes, please.
There wasn't a minimal intention, more like a basic setup. So, It would be very good.

Gretings!
Aldo.

**Comment by ArgonQQ** [comment]
Ok. Will push some updates tomorrow or later this week. 

Greetings
~ ArgonQQ

**Pull request merged**
